# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 23:32
# from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browserHash', models.CharField(help_text=b'Hash of HTTP headers in session to prevent impersonization', max_length=64)),
                ('user', models.CharField(help_text=b'User name', max_length=128)),
                ('securityToken', models.CharField(help_text=b'Obtained Security Token', max_length=256)),
                ('retryToken', models.CharField(help_text=b'Obtained Retry Token', max_length=256)),
            ],
        ),
    ]
