# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='sessionID',
            new_name='sessionid',
        ),
    ]
